"""Original English clues and topic games. No textbook exercises copied."""
import json, pathlib, random
root = pathlib.Path(__file__).resolve().parent.parent
data = json.loads((root/'content/en/A1.json').read_text())
# One clue per lexical entry, in the established unit order. Short French
# translations remain available as explanations; options use different concepts.
clues = [
'''A greeting: you can say this when you meet someone.;You say this when you leave.;You add this word when you ask for something politely.;You say these two words after someone helps you.;You say this when your answer is positive.;You say this when your answer is negative.;You say this when you make a mistake.;A greeting for the start of the day.;You say this before someone goes to bed.;A question about how a person feels.;I am not sick or sad. I feel ___.;These three words introduce your name.;You say this when you meet a person for the first time.;You say this to a new visitor.;You will meet again in a short time.;You say this politely to get someone's attention.;A polite reply to thank you.;Use this question word to ask about a thing.;Use this question word to ask about a place.;Use this question word to ask about a person.;A person you like and spend time with.;Lina is my ___. People call me Lina.;Use this pronoun to talk about yourself.;Use this pronoun to talk directly to another person.;The opposite of bad.;A short, informal greeting.;A short, informal goodbye.;A greeting between lunch and the evening.;A greeting when the evening begins.;You will meet again on the next day.;A question that asks a person's age.;These words introduce the place you come from.;Algeria and Japan are examples of this.;London and Paris are examples of this.;Your house number and street name.;The digits someone uses to call you.;Say or write the same thing again.;Use words to talk.;Do something at a low speed.;The language used in London and this course.''',
'''Your female parent.;Your male parent.;A girl who has the same parents as you.;A boy who has the same parents as you.;Your mother's mother.;Your father's father.;A very young child.;Your parents, brothers and sisters belong to this group.;A young person who is not an adult.;Your mother's sister.;Your father's brother.;Your aunt's child.;The man a person is married to.;The woman a person is married to.;Someone's male child.;Someone's female child.;Your mother and father together.;The opposite of young.;The opposite of old.;Feel very close to someone and care about them.;The place where you live.;We are not apart. We are ___.;I smile because I am ___.;The pronoun for one boy or man.;The pronoun for one girl or woman.;The plural of person.;An adult male person.;An adult female person.;A person aged thirteen to nineteen.;A person who is no longer a child.;Someone who lives next door.;One human being.;The pronoun for me and you together.;The pronoun for several other people.;It belongs to us: it is ___ house.;It belongs to them: it is ___ house.;It belongs to me: it is ___ bag.;It belongs to you: it is ___ bag.;Have your home in a place.;Go to see someone at their home.''',
'''A round fruit that can be red or green.;You can make toast from this food.;A white drink from cows.;A clear drink with no colour.;A hen lays this.;Small white grains you can cook and eat.;A farm bird and a kind of meat.;An animal that lives in water and can be food.;A long yellow fruit.;A round red food often used in salad.;A food made from milk, often used in sandwiches.;A round citrus fruit.;A sweet food often eaten on birthdays.;A liquid food served in a bowl.;A drink made from fruit.;A hot drink made from dark beans.;You want food because you are ___.;You want water because you are ___.;Put food in your mouth.;Take water or juice into your mouth.;The food tastes very good. It is ___.;Sugar makes food taste ___.;The soup has a high temperature. It is ___.;The juice is from the fridge. It is ___.;The first meal of the day.;A vegetable often used to make chips.;A long orange vegetable.;A vegetable that can make your eyes water when you cut it.;A dish of vegetables, often with lettuce.;Food such as spaghetti.;A yellow food you can spread on bread.;A white food seasoning that is not sweet.;Sweet white grains used in cakes.;A drink made by putting leaves in hot water.;The meal around the middle of the day.;The main meal often eaten in the evening.;A flat dish that holds food.;A small container for tea.;You use this to eat soup.;You use this to pick up pieces of food.''',
'''A pet that barks.;A pet that says meow.;An animal with feathers.;An animal with fins that lives in water.;A small animal with long ears.;A large animal people can ride.;A farm animal that gives milk.;A very large animal with a long trunk.;A large wild cat. The male has a mane.;An animal with hands that often climbs trees.;A long animal with no legs.;A small animal that jumps and lives near water.;A large animal that can be brown or black.;A bird that swims and says quack.;An insect with large colourful wings.;The opposite of small.;The opposite of big.;The opposite of slow.;The opposite of fast.;Small and nice to look at.;This adjective means not tame.;A general word for an animal kept at home.;Move through the air.;Move quickly on your legs.;Move through water.;A farm animal with wool.;A farm animal with horns that can give milk.;A farm animal often shown as pink.;A very small animal with a long thin tail.;A large wild cat with dark stripes.;A very tall animal with a long neck.;An animal with black and white stripes.;An animal with a hard shell.;An insect that makes honey.;A very small insect that lives in a large group.;An animal with eight legs.;The long part at the back of a cat's body.;A body part that a bird uses to fly.;Give food to a person or animal.;Rest with your eyes closed at night.''',
'''The colour of a ripe tomato.;The usual colour of a clear daytime sky.;The colour of most grass.;The colour of a ripe banana.;The darkest colour.;The colour of fresh snow.;The colour of a carrot.;A pale colour between red and white.;A colour made by mixing red and blue paint.;The colour of chocolate.;A colour between black and white.;A pale shade of blue.;With little or no light.;The opposite of dark.;Red, blue and green are examples of this.;A band of colours in the sky after rain.;Put colour on a wall with a brush.;The space above us where clouds appear.;The short green plants that cover a lawn.;The one you like best.;Very nice to look at.;The colourful part of a plant.;The bright object that gives us daylight.;The large area of salty water.;Use your eyes.;A shiny colour like some metal spoons.;A shiny yellow metal colour.;A deep shade of blue.;A pale shade of green.;A deep shade of green.;Strong and easy to see, like a very strong colour.;Not a strong or deep colour.;With many different colours.;An image of a person, place or thing.;An image made with a pencil.;Make a picture with a pencil.;A tool used to put paint on paper.;The material in a notebook.;A flat green part of a plant.;A small bright point in the night sky.''',
'''The number after zero.;The number after one.;The number after two.;The number after three.;The number after four.;The number after five.;The number after six.;The number after seven.;The number after eight.;The number after nine.;The number after ten.;The number after eleven.;The number after nineteen.;Ten times ten.;No things at all.;The position before second.;The final position in a line.;Say numbers to find how many things there are.;A bigger amount, not a smaller amount.;A smaller amount, not a bigger amount.;A large number of things.;A small number of things.;How old a person is.;Twelve months.;One of two equal parts.;The number after twelve.;The number after thirteen.;The number after fourteen.;The number after fifteen.;The number after sixteen.;The number after seventeen.;The number after eighteen.;Three groups of ten.;Four groups of ten.;Five groups of ten.;Six groups of ten.;The position after first.;The position after second.;A symbol such as 4 or 9.;The sign in 2 + 3, written as a word.''',
'''The place where children go to learn.;A person who teaches a class.;A person who learns in a class.;Many pages joined together, often with a story.;You write with this and can erase it.;You write with this using ink.;You carry your books in this.;A table where a student works.;A room where a class learns.;A period of learning with a teacher.;School work you do at home.;A test of what you know.;Something you ask.;A reply to a question.;Look at written words and understand them.;Put words on paper.;Get new knowledge or a new skill.;Spend time learning a subject.;Know what something means.;Not easy.;Not difficult.;Right, with no mistake.;Not correct.;A group of students learning together.;A place where you can borrow books.;A small book for your own writing.;You use this to remove pencil marks.;A tool for drawing straight lines.;A large surface the teacher writes on.;An electronic machine used for work and study.;The part of a computer where you see words and pictures.;The part of a computer with letter keys.;A book that explains what words mean.;One side of a sheet in a book.;A group of words such as I like apples.;A unit of language such as cat.;Use your ears to pay attention.;Say a question.;Do an activity again to get better at it.;Make a task easier for someone.''',
'''A building where people live.;A separate space inside a house.;You open this to enter a room.;You look through this to see outside.;The room where you cook.;The room where you sleep.;The room with a bath or shower.;The room where a family sits and relaxes.;An outdoor area with plants near a house.;Furniture with a flat top for meals.;Furniture for one person to sit on.;Furniture where you sleep.;An object that gives light.;A machine that keeps food cold.;Steps between floors.;A vertical part at the side of a room.;The surface you walk on inside.;The top part that covers a house.;Not dirty.;Move a door so people can enter.;Move a door so people cannot enter.;In a building or container.;Not inside.;On a higher floor.;On a lower floor.;A long soft seat for several people.;You can see your own face in this.;A soft covering for the floor.;A flat board where you can put books.;Furniture with doors for storing things.;A machine you use to bake food.;A bowl with a tap for washing things.;Water falls from this when you wash your body.;You sit on this in the bathroom.;A small object used to unlock a door.;You use this to dry your body.;A soft object under your head in bed.;A cover that keeps you warm in bed.;In a lower position than something.;At the back of something.''',
'''The part of your body above your neck.;You use this body part to see.;You use this body part to smell.;You open this to eat.;You use this body part to hear.;The part at the end of your arm.;One body part at the end of a leg.;The body part between your shoulder and hand.;The body part between your hip and foot.;The rear part of your body.;Food goes here after you eat.;This grows on your head.;The front of your head.;The hard white things in your mouth.;One of the long parts on your hand.;The joint in the middle of your leg.;The body part where your arm joins your body.;Not well.;Feel pain or cause pain.;Able to lift heavy things.;Clean yourself with water.;You need sleep because you feel ___.;Your head, arms and legs are parts of this.;The side opposite right.;The side opposite left.;The body part between your head and shoulders.;One of the small parts at the end of your foot.;The short, thick part at the side of your hand.;The joint in the middle of your arm.;The part of your face below your mouth.;One of the soft edges of your mouth.;One hard white thing in your mouth.;The plural of foot.;Well and not sick.;A person who treats people who are sick.;A person who cares for patients, often in a hospital.;Something you take to help you get well.;Stop working for a while.;Move on your feet, not by running.;Show that you are happy with your mouth.''',
'''Clothes for the upper body, often with a collar.;Clothes with two long legs.;One piece of clothing with a skirt and a top.;You wear these on your feet outdoors.;A covering for your head.;A long warm outer piece of clothing.;You wear these inside your shoes.;You wear these on your hands.;A long piece of clothing around your neck.;Clothes from the waist down, with no separate legs.;A short outer piece of clothing.;You wear these in front of your eyes to see better.;You carry your things in this.;A strip you wear around your waist.;Clothes for sleeping.;Have clothes on your body.;Not used before.;Not new.;Not cold.;Nice to wear, not too tight or rough.;Start wearing a piece of clothing.;Remove a piece of clothing.;Small, medium and large are examples of this.;Red or blue, for example.;A place where you buy things.;A casual short-sleeved top with no collar.;Trousers often made of blue denim.;Clothes with two short legs.;A warm knitted top.;Shoes that cover your ankles or more.;Shoes often used for sport.;A soft hat with a short front part.;Clothes you wear to swim.;A small space in clothes for carrying things.;A small round object used to fasten clothes.;A size for a smaller body.;A size for a bigger body.;Get something by paying money.;How much something costs.;Put on clothes in a shop to check the fit.''',
'''The bright object in the sky during the day.;Water falling from clouds.;Soft white things falling from clouds in cold weather.;Air that moves.;A white or grey shape in the sky.;Bad weather with strong wind and often rain.;The opposite of cold.;The opposite of hot.;With a lot of sunshine.;With rain.;With many clouds.;With snow.;With a lot of wind.;A little hot, but not very hot.;You hold this over your head in the rain.;Rain, wind and sunshine are examples of this.;One of the four parts of a year.;The season after winter.;The season after spring.;The season after summer.;The season after autumn.;The loud sound that can follow lightning.;Cloud close to the ground that makes it hard to see.;Not inside a building.;How hot or cold something is.;A little cold, but not very cold.;Not wet.;Covered with water.;Water that is frozen.;A person-shaped figure made from snow.;A coat that keeps rain off your clothes.;Information about tomorrow's weather.;A unit for measuring temperature.;The gas around us that we breathe.;There are no clouds: the ___.;Water is falling from clouds: ___.;Snow is falling now: ___.;The sun is shining now: ___.;The wind is blowing now: ___.;The temperature is high: ___.''',
'''The day after Sunday.;The day after Monday.;The day after Tuesday.;The day after Wednesday.;The day after Thursday.;The day after Friday.;The day after Saturday.;The part of the day before noon.;The part of the day after noon and before evening.;The part of the day between afternoon and night.;The dark part of the day.;The day we are in.;The day before today.;The day after today.;Seven days.;A part of a year such as January.;Sixty minutes.;Sixty seconds.;At this moment.;Every time, with no exceptions.;Not at any time.;Before the expected time.;After the expected time.;An object that shows the time.;Saturday and Sunday together.;The day, month and year of an event.;A chart that shows days and months.;The day you celebrate being born.;A period of twenty-four hours.;During the night of today.;Once each day.;On all days.;At twelve in the middle of the day.;Twelve at night.;Thirty minutes after an hour.;Fifteen minutes after an hour.;Fifteen minutes before an hour.;Earlier than something.;Later than something.;At the expected time, neither early nor late.'''
]

# Exclude interchangeable answers and broad/narrow alternatives from a clue's
# distractors, including informal greetings and pronoun/kinship overlaps.
aliases = [
    {'hello','hi','welcome','good morning','good afternoon','good evening'},
    {'goodbye','bye','good night','see you soon','see you tomorrow'},
    {'excuse me','sorry','hello','hi'},
    {'fine','good','happy','healthy'}, {'friend','person','people','neighbour'},
    {'child','baby','teenager','young'}, {'mother','parents','family','grandmother'},
    {'father','parents','family','grandfather'}, {'sister','daughter','woman'},
    {'brother','son','man'}, {'adult','man','woman','person','people'},
    {'we','our'},{'they','their'},{'I','my'},{'you','your'},
    {'hot','warm'},{'cold','cool'},{'big','large size'},{'small','small size'},
    {'colour','red','blue','green','yellow','orange','pink','purple','brown','grey','black','white','silver','gold','light blue','dark blue','light green','dark green'},
    {'picture','drawing'},{'light','bright','pale'},{'sun','star'},
    {'cup','plate'},{'milk','water','juice','tea','coffee'},
    {'bird','duck'},{'cow','goat'},{'pet','dog','cat','rabbit','bird','fish'},
    {'foot','feet'},{'tooth','teeth'},{'head','face'},{'finger','thumb'},
    {'coat','jacket','raincoat'},{'hat','cap'},{'shirt','T-shirt','jumper'},
    {'trousers','jeans'},{'shoes','trainers','boots'},{'shop','buy'},
    {'rain','rainy','it is raining'},{'snow','snowy','it is snowing'},
    {'sun','sunny','it is sunny'},{'wind','windy','it is windy'},
    {'hot','it is hot'},{'always','daily','every day'},{'night','tonight','midnight'},
    {'first','one'},{'second','two'},{'third','three'}, {'many','more'},{'few','less'},
    {'name','my name is'}, {'hour','half past','quarter past','quarter to'},
    {'doctor','nurse'}, {'cheese','butter'}, {'library','book','dictionary'},
    {'room','kitchen','bedroom','bathroom','living room'},
    {'chair','sofa'}, {'floor','carpet'}, {'cupboard','fridge'},
    {'wear','put on'}, {'dark','black','dark blue','dark green'},
    {'wind','air'},{'cloud','cloudy','fog'},
    {'season','spring','summer','autumn','winter'},
    {'temperature','degree'}, {'birthday','date'}, {'count','number'},
]

additional=[]
for ui, unit in enumerate(data['units']):
    definitions=clues[ui].split(';')
    assert len(definitions)==40, (ui,len(definitions))
    rng=random.Random(20261010+ui)
    for wi,(word,clue) in enumerate(zip(unit['words'],definitions)):
        excluded={word['t']}
        for group in aliases:
            if word['t'] in group: excluded |= group
        candidates=[w for w in unit['words'] if w['t'] not in excluded]
        rng.shuffle(candidates)
        options=[word['t']]+[w['t'] for w in candidates[:3]]
        additional.append(dict(id=f'en-a1-u{ui}-clue-{wi}',unitIndex=ui,type='choice',prompt='Which word or phrase has this meaning?',passage=clue,choices=options,answer=0,objective='vocabulary-in-context',explanation=f"{word['t']} : {word['fr']}. Indice : {clue}"))
    # Forty different four-pair rounds, with no duplicated translation and
    # balanced exposure: each lexical entry occurs exactly four times.
    used={tuple(sorted(w['id'] for w in unit['words'][:4]))}
    exposure={w['id']:0 for w in unit['words']}
    for mi in range(40):
        for attempt in range(10000):
            candidates=list(unit['words']);rng.shuffle(candidates)
            candidates.sort(key=lambda w:exposure[w['id']])
            pairs=candidates[:4]
            key=tuple(sorted(w['id'] for w in pairs))
            if key not in used and len({w['fr'].lower() for w in pairs})==4: break
        else: raise ValueError('Cannot build matching set')
        used.add(key)
        for w in pairs: exposure[w['id']]+=1
        additional.append(dict(id=f'en-a1-u{ui}-pairs-{mi}',unitIndex=ui,type='match',pairIds=[w['id'] for w in pairs],objective='vocabulary-review'))
    assert set(exposure.values())=={4}, (ui,exposure)

# Five additional original everyday contexts per unit; two different questions
# test comprehension of each. These are not copies of the existing microtexts.
readings=[
'''Nina meets a new student at school. She says, Hello, I am Nina. The student says, I am Karim. I am from Morocco.|Who is from Morocco?|Karim|Nina|Their teacher|Both students|Where do they meet?|At school|At a shop|On a train|At the beach
Leo: Can you repeat your name, please? Amira: Amira. Leo: Thank you, Amira.|What does Leo ask Amira to repeat?|Her name|Her address|Her age|Her phone number|What does Leo say after she repeats it?|Thank you|Good night|Goodbye|Welcome
My friend is called Mei. She lives in Tokyo. I live in Algiers. We write messages in English.|Where does Mei live?|Tokyo|Algiers|London|Paris|Which language do the friends use in their messages?|English|French|Spanish|German
It is six in the evening. Daniel arrives at his neighbour's house. He says, Good evening. His neighbour says, Welcome!|When does Daniel arrive?|In the evening|In the morning|At noon|At midnight|Whose house does Daniel visit?|His neighbour's house|His teacher's house|His cousin's house|His grandfather's house
The form asks for my name and phone number. My name is Aya. My number is 0612345678.|What two things does the form ask for?|Name and phone number|Age and city|Country and age|Address and birthday|What is the person's name?|Aya|Maya|Anna|Eva''',
'''I have a sister called Sarah. We visit our uncle on Sundays. He lives next door to our grandmother.|Who visits the uncle with the speaker?|Sarah|Their father|Their mother|Their grandfather|Who lives next door to the uncle?|The grandmother|The sister|The teacher|The cousin
Rami's father has a brother called Nabil. Nabil has a daughter called Hala.|Who is Nabil to Rami?|His uncle|His brother|His cousin|His grandfather|Who is Hala to Rami?|His cousin|His mother|His aunt|His grandmother
My parents work on Saturday. My grandfather stays at home with my little sister. I visit my cousin.|Who stays with the little sister?|The grandfather|The cousin|The parents|The teacher|What does the speaker do?|Visit a cousin|Go to work|Visit a teacher|Stay with the sister
Three people live in our home: my mother, my brother and me. My father lives in another city.|How many people live in the speaker's home?|Three|Two|Four|Five|Who lives in another city?|The father|The mother|The brother|The speaker
My neighbour is an adult. Her son is a teenager. Her daughter is a baby.|Who is a teenager?|The neighbour's son|The neighbour|The neighbour's daughter|The speaker's mother|Who is a baby?|The neighbour's daughter|The neighbour's son|The neighbour|The speaker's father''',
'''Amina makes soup with carrots and onions. She serves it with bread. She does not use potatoes.|Which vegetables are in the soup?|Carrots and onions|Potatoes and tomatoes|Carrots and potatoes|Tomatoes and onions|What does she serve with the soup?|Bread|Pasta|Rice|Cake
I am thirsty after football. There is milk in the fridge, but I choose a glass of water.|How does the speaker feel?|Thirsty|Sleepy|Cold|Sick|What does the speaker choose?|Water|Milk|Coffee|Juice
Our picnic is at noon. We bring salad, cheese and apples. Mum brings forks and plates.|When is the picnic?|At noon|At midnight|Before breakfast|Late at night|Who brings the plates?|Mum|Dad|The speaker|The grandmother
The café has tea for two pounds and coffee for three pounds. I buy tea and a piece of cake.|Which drink costs two pounds?|Tea|Coffee|Juice|Milk|What food does the speaker buy?|Cake|Soup|Salad|Rice
For dinner, we cook pasta with tomatoes. We add a little salt. We do not add sugar.|What do they cook?|Pasta|Rice|Fish|Chicken|What do they add?|Salt|Sugar|Butter|Milk''',
'''At the zoo, we see a giraffe beside a tree. Two zebras stand near it. The tiger is in another area.|Which animal is beside the tree?|The giraffe|The tiger|An elephant|A bear|How many zebras are there?|Two|One|Three|Four
Our rabbit eats a carrot in the morning. At night, it sleeps in a small box.|What does the rabbit eat?|A carrot|Cheese|Bread|Fish|Where does it sleep?|In a small box|In a tree|In the water|Under a car
A bee is on a flower. An ant is on the ground. A butterfly flies above the flower.|Which insect is on the ground?|The ant|The bee|The butterfly|A spider|Which insect is flying?|The butterfly|The ant|The bee|A spider
The farmer feeds the pigs at seven. She feeds the sheep at eight. The horses eat at nine.|Which animals eat first?|The pigs|The sheep|The horses|The cows|When do the horses eat?|At nine|At seven|At eight|At ten
My cat has a long tail. It is small and grey. It sleeps on a warm chair.|What is long?|The cat's tail|The cat's ears|The chair's legs|The cat's wings|What colour is the cat?|Grey|White|Orange|Black''',
'''Yara paints a yellow sun and a blue sea. She uses green paint for the grass.|What colour is the sea in Yara's picture?|Blue|Yellow|Green|Red|What does Yara paint green?|The grass|The sun|The sea|The sky
My favourite colour is purple. My sister likes pink. We buy a purple notebook for me and a pink one for her.|What colour is the speaker's notebook?|Purple|Pink|Green|Grey|Who likes pink?|The sister|The speaker|The mother|The father
There are three brushes on the paper. One brush has red paint. The other two have black paint.|How many brushes have black paint?|Two|One|Three|Four|Where are the brushes?|On the paper|Under the chair|In a bag|On the floor
The picture has a brown house with a white door. There is a green tree beside it.|What colour is the door?|White|Brown|Green|Black|What is beside the house?|A green tree|A brown boat|A white car|A black chair
I draw a star with a pencil. Then I colour it gold. My friend draws a silver moon.|What does the speaker draw?|A star|A moon|A flower|A leaf|What colour is the friend's moon?|Silver|Gold|Blue|Yellow''',
'''There are fifteen chairs in the room. Twelve students sit down. Three chairs are empty.|How many students sit down?|Twelve|Fifteen|Three|Ten|How many chairs are empty?|Three|Twelve|Fifteen|Two
Maya is first in the race. Ali is second. Noor is third. There are ten runners.|Who is second?|Ali|Maya|Noor|The teacher|How many runners are there?|Ten|Three|Two|Twelve
I buy four oranges and six apples. My bag has ten pieces of fruit.|How many oranges does the speaker buy?|Four|Six|Ten|Two|How many pieces of fruit are in the bag?|Ten|Four|Six|Eight
Our classroom number is thirty. The library is room forty. The music room is fifty.|Which room is the library?|Forty|Thirty|Fifty|Twenty|What is in room fifty?|The music room|The library|The classroom|The office
I have twenty euros. I spend five euros on a notebook. I have fifteen euros left.|How much does the notebook cost?|Five euros|Twenty euros|Fifteen euros|Ten euros|How much money is left?|Fifteen euros|Five euros|Twenty euros|Ten euros''',
'''Our teacher writes a question on the board. We write our answers in our notebooks. Then we read them to a partner.|Where is the question?|On the board|In a dictionary|On the window|On the floor|Where do students write their answers?|In their notebooks|On the board|In library books|On the window
Hana cannot find her ruler. Her friend gives her a ruler. Hana can now draw a straight line.|What does Hana need?|A ruler|A dictionary|A keyboard|An eraser|Who helps Hana?|Her friend|Her father|Her neighbour|Her grandmother
On Friday, our class goes to the library. Each student chooses one book. We return the books the next Friday.|Where does the class go?|To the library|To the gym|To a café|To the beach|How many books does each student choose?|One|Two|Three|Four
The homework is on page eighteen. Write five sentences. Bring your notebook on Tuesday.|Which page has the homework?|Eighteen|Eight|Fifteen|Twenty|How many sentences must students write?|Five|Eighteen|Three|Ten
I study English on my computer. I read a short text on the screen. Then I type three answers with the keyboard.|What does the speaker read?|A short text|A shopping list|A train ticket|A menu|What does the speaker use to type?|The keyboard|A ruler|An eraser|A pencil''',
'''The bathroom is upstairs. The kitchen is downstairs. Our bedrooms are next to the bathroom.|Where is the kitchen?|Downstairs|Upstairs|Outside|On the roof|What is next to the bathroom?|The bedrooms|The garden|The kitchen|The garage
We put clean towels in the cupboard. There is a mirror above the sink. The shower is beside the sink.|Where are the towels?|In the cupboard|In the sink|On the mirror|In the shower|What is above the sink?|A mirror|A cupboard|A towel|A shower
The door is closed, but the window is open. A black cat sits outside the window.|What is open?|The window|The door|The cupboard|The oven|Where is the cat?|Outside the window|Inside the oven|Under the bed|Behind the sofa
I put my pillow on the bed and my blanket over it. My book is on the shelf, not on the bed.|Where is the book?|On the shelf|On the bed|Under the pillow|In the fridge|What is over the pillow?|The blanket|The book|The shelf|The chair
There is a sofa in the living room. We put a carpet in front of it. A lamp stands behind the sofa.|What is in front of the sofa?|A carpet|A lamp|A fridge|A sink|Where is the lamp?|Behind the sofa|On the carpet|In the kitchen|Under the sofa''',
'''After the game, my feet are dirty. I wash them with water and dry them with a towel.|What does the speaker wash?|Their feet|Their hair|Their hands|Their face|What does the speaker use to dry them?|A towel|A blanket|A pillow|A scarf
Leila has a sore throat. The doctor asks her to open her mouth. Her brother waits outside.|Who asks Leila to open her mouth?|The doctor|Her brother|Her teacher|Her father|Where does her brother wait?|Outside|Beside the doctor|In Leila's bedroom|At school
In our drawing, the person has short hair and blue eyes. The person has a smile and wears a green hat.|What colour are the eyes?|Blue|Green|Brown|Grey|What is short?|The hair|The hat|The arms|The legs
I carry my bag with my right hand. My left hand holds a book. I put the book on the desk.|Which hand holds the book?|The left hand|The right hand|Both hands|Neither hand|Where does the speaker put the book?|On the desk|In the bag|Under the chair|On the bed
After a long walk, Dad is tired. He sits down and rests. His children play quietly in the next room.|How does Dad feel?|Tired|Hungry|Angry|Cold|What does Dad do?|Sit down and rest|Go swimming|Cook dinner|Run outside''',
'''I put on my trainers for football. My boots are by the door. My swimsuit is in a drawer.|What does the speaker wear for football?|Trainers|Boots|A swimsuit|Pyjamas|Where are the boots?|By the door|In a drawer|Under the bed|In a bag
At the shop, I try on a small jacket. It is too small. The assistant brings a large jacket, and it fits.|Which jacket fits?|The large jacket|The small jacket|Both jackets|Neither jacket|Where is the speaker?|At a shop|At school|At a hospital|At a library
Meriem's dress has two pockets. She puts her phone in the right pocket and her key in the left pocket.|What is in the right pocket?|The phone|The key|A coin|A pen|How many pockets does the dress have?|Two|One|Three|Four
Before going to bed, I take off my jeans and put on my pyjamas. I leave my jeans on the chair.|What does the speaker put on?|Pyjamas|Jeans|A coat|A swimsuit|Where are the jeans left?|On the chair|In the shower|Under the bed|On the shelf
My new scarf costs eight pounds. My old hat has a hole. Today I buy a new hat for six pounds.|How much does the new hat cost?|Six pounds|Eight pounds|Four pounds|Ten pounds|Which old item has a hole?|The hat|The scarf|The coat|The jumper''',
'''The forecast says rain in the morning and sunshine in the afternoon. We plan to walk in the afternoon.|When is rain expected?|In the morning|In the afternoon|At midnight|In the evening|When do they plan to walk?|In the afternoon|In the morning|At midnight|Before breakfast
There is fog on the road. Dad drives slowly. The car windows are closed because the air is cold.|Why does Dad drive slowly?|There is fog|The road is empty|It is very hot|The sky is clear|What is cold?|The air|The tea|The dinner|The oven
In winter, the lake has ice on it. In summer, people swim in the lake. We do not walk on the ice.|When do people swim in the lake?|In summer|In winter|Every snowy day|At midnight|What is on the lake in winter?|Ice|Sand|Leaves|Grass
The children make a snowman. They give it a hat and a carrot nose. Then they go inside for a warm drink.|What do they make?|A snowman|A sandcastle|A cake|A kite|What do they use for its nose?|A carrot|An apple|A potato|A banana
It is twenty degrees today. Yesterday it was ten degrees. Today is warmer than yesterday.|What is today's temperature?|Twenty degrees|Ten degrees|Thirty degrees|Zero degrees|Which day is warmer?|Today|Yesterday|Both are the same|The text does not say''',
'''My birthday is on Wednesday. Today is Monday. Tomorrow I buy a cake, and on Wednesday my friends visit.|What day is the birthday?|Wednesday|Monday|Tuesday|Friday|When does the speaker buy a cake?|Tuesday|Monday|Wednesday|Sunday
The bus leaves at quarter past nine. I arrive at nine. I wait fifteen minutes.|What time does the bus leave?|Nine fifteen|Nine|Nine thirty|Eight forty-five|How long does the speaker wait?|Fifteen minutes|Five minutes|Thirty minutes|One hour
I study every day from five to six. On Saturday, I also play tennis at ten in the morning.|How long does the speaker study each day?|One hour|Two hours|Thirty minutes|Five hours|When does the speaker play tennis?|Saturday morning|Saturday evening|Sunday morning|Friday afternoon
We have lunch at noon. Before lunch, we wash our hands. After lunch, we go back to class.|When do they wash their hands?|Before lunch|After lunch|At midnight|After class|Where do they go after lunch?|Back to class|To bed|To the beach|To the shop
The film starts at half past six. We arrive at quarter past six. We are early.|What time does the film start?|Six thirty|Six fifteen|Six forty-five|Seven|How are they described when they arrive?|Early|Late|Exactly on time|Absent'''
]
for ui,rows in enumerate(readings):
    for ri,row in enumerate(rows.splitlines()):
        passage,*fields=row.split('|')
        assert len(fields)==10
        for qi in range(2):
            prompt,*options=fields[qi*5:qi*5+5]
            additional.append(dict(id=f'en-a1-u{ui}-extra-reading-{ri}-{qi}',unitIndex=ui,type='choice',passage=passage,prompt=prompt,choices=options,answer=0,objective='reading-comprehension',explanation=f"Réponse : {options[0]}. Le texte précise : {passage}"))
assert len(additional)==1080
(root/'content/en/A1-expanded.json').write_text(json.dumps(additional,ensure_ascii=False,indent=2)+'\n')
print(f'{len(additional)} contextual clues and matching games authored')
